### ISSUE TITLE
Failing release for Linux, 32-bit

### ISSUE THREAD

**Issue by hariso** [conduitio-labs/conduit-connector-weaviate#48]
### Bug description

Our v0.1.0 failed with the following error:

```
  ⨯ release failed after 3m27s               error=failed to build for linux_386: exit status 1: # github.com/weaviate/weaviate/entities/vectorindex/common
Error: ../../../go/pkg/mod/github.com/weaviate/weaviate@v1.26.0-rc.1/entities/vectorindex/common/config.go:59:14: constant 9223372036854775807 overflows int
```

[Link to GitHub action](https://github.com/conduitio-labs/conduit-connector-weaviate/actions/runs/10940775560)

### Steps to reproduce

Run `goreleaser release --snapshot`.

### Version

v0.1.0

**Comment by hariso** [comment]
The size of `int` in Go depends on the architecture (32-bit vs 64-bit). In this case, the release is failing for a 32-bit, because constant 9223372036854775807 cannot fit into a 32-bit integer. This constant is in a 3rd party library, so it looks like we cannot do much about this, except to remove Linux 32-bit from our builds.

**Comment by lovromazgon** [comment]
Yeah, let's remove the OS/arch target.
